### ISSUE TITLE
Availability for Spark 3.x

### ISSUE THREAD

**Issue by n8shadow** [fqaiser94/mse#18]
I absolutely love this package! I'm far from being a Spark/Scala pro but it makes my live so much easier working with jsons and transforming them.
However, executing it with Spark 3.1 and Scala 2.12 I am getting the following error:
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
How can I make it available for Spark 3.x? Thx!

**Comment by fqaiser94** [comment]
Hi @n8shadow , thanks! 

Regarding your issue, I don't recall having any issues running this package on Spark 3.0 (and would have assumed it would just work on Spark 3.1) yet but typically, I see the error you're facing when I'm using the wrong scala version (e.g. `2.11` instead of `2.12` or vice versa). Just wanted to make sure you've already checked this? 

Also, you mention you're using Spark **3.1**. I assume you've built a custom version of that from the Spark 3.1 branch since AFAIK this hasn't been released to the public yet. If so, you actually shouldn't need this library anymore! I've contributed the methods back to open-source Apache Spark and they should already be present in the Spark 3.1 branch.

**Comment by n8shadow** [comment]
Hi @fqaiser94 ,

I am using Databricks and was facing these error for runtime 7.3 ML LTS. Sorry it was a typo the correct Spark version is 3.0.1.

I'm looking forward to have this great contribution comming live with Spark 3.1; thanks!

**Comment by fqaiser94** [comment]
@n8shadow I just tried this on Databricks Runtime 7.3 ML LTS (Spark 3.0.1, **Scala 2.12**) and everything worked fine for me using the `mse_2.12` jar. 
I was able to reproduce the same error you were facing when I used the wrong scala version of the jar i.e. `mse_2.11` jar. I would advise you to make sure you're using the `mse_2.12` jar.

**Comment by n8shadow** [comment]
@fqaiser94 Thank you for the hint, now everthing is working as expected! Again, much respect!
